#!/bin/bash
apt-get install -y --force-yes lintian > /dev/null

cd /tmp/buildd/*/debian/..

echo "Running Lintian ..."
lintian --allow-root \
	--suppress-tags debian-changelog-file-contains-invalid-email-address \
	--suppress-tags debian-watch-file-in-native-package \
	--suppress-tags newer-standards-version \
	|| true
echo "Done"
